# Generated by Django 2.1.2 on 2018-10-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cidade',
            table='cidade',
        ),
    ]
