# Generated by Django 2.1.2 on 2018-10-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181021_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='escolas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_alunos', models.IntegerField(max_length=10)),
                ('renda', models.CharField(max_length=100)),
                ('ocorrencias', models.CharField(max_length=100)),
                ('quantidade_professores', models.IntegerField(max_length=10)),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'escolas',
            },
        ),
    ]
