# Generated by Django 2.1.2 on 2018-10-21 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='provas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'provas',
            },
        ),
        migrations.CreateModel(
            name='questoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=1000)),
                ('imagem', models.ImageField(null=True, upload_to='imagens')),
                ('alternativas', models.CharField(max_length=1, null=True)),
                ('gabarito', models.CharField(max_length=1, null=True)),
                ('disciplina', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'questoes',
            },
        ),
        migrations.AddField(
            model_name='provas',
            name='questoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geracao_prova.questoes'),
        ),
    ]
