# Generated by Django 2.1.2 on 2018-10-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao_prova', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoes',
            name='disciplina',
            field=models.CharField(max_length=50),
        ),
    ]
