# Generated by Django 2.1.2 on 2018-10-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geracao_prova', '0002_auto_20181021_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questoes',
            name='alternativas',
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='gabarito',
        ),
    ]
