# Generated by Django 2.1.2 on 2018-10-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao_prova', '0003_auto_20181021_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='questoes',
            name='alternativas',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='questoes',
            name='gabarito',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
