# Generated by Django 2.1.2 on 2018-10-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao_prova', '0004_auto_20181021_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provas',
            name='questoes',
            field=models.CharField(max_length=9999),
        ),
    ]
